### ISSUE TITLE
windows os working well, when deploy to ubuntu, the output docx file can't open correctly

### ISSUE THREAD

**Issue by lling1105** [evidenceprime/html-docx-js-node-sample#1]
i paste the html file and the output docx as your reference
------------------------------html file---------------------------------
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title></title>
    <meta name="generator" content="LibreOffice 4.2.6.3 (Linux)">
    <meta name="created" content="20160112;33755000000000">
    <meta name="changed" content="0;0">
    <style type="text/css">
    
    </style>
</head>
<body lang="en-US" text="#00000a" dir="ltr">

<p class="western" style="margin-bottom: 0in; line-height: 100%">abc</p>

</body>
</html>

------------------------output docx--------------------------------------
PK
\00\00\00\00\00B,H\96%v\96\D1\00\00\D1\00\00\00\00\00[Content_Types].xml<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType=
    "application/vnd.openxmlformats-package.relationships+xml" />
  <Override PartName="/word/document.xml" ContentType=
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/afchunk.mht" ContentType="message/rfc822"/>
</Types>
PK
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00_rels/PK
\00\00\00\00\00B,H\C2/\E5J\00\00J\00\00\00\00\00_rels/.rels<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship
      Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"
      Target="/word/document.xml" Id="R09c83fafc067488e" />
</Relationships>
PK
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00word/PK
\00\00\00\00\00B,H"?!\E0\00\00\00\00\00\00\00word/document.xml<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document
  xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
  xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
  xmlns:ns6="http://schemas.openxmlformats.org/schemaLibrary/2006/main"
  xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart"
  xmlns:ns8="http://schemas.openxmlformats.org/drawingml/2006/chartDrawing"
  xmlns:dgm="http://schemas.openxmlformats.org/drawingml/2006/diagram"
  xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"
  xmlns:ns11="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing"
  xmlns:dsp="http://schemas.microsoft.com/office/drawing/2008/diagram"
  xmlns:ns13="urn:schemas-microsoft-com:office:excel"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:ns17="urn:schemas-microsoft-com:office:powerpoint"
  xmlns:odx="http://opendope.org/xpaths"
  xmlns:odc="http://opendope.org/conditions"
  xmlns:odq="http://opendope.org/questions"
  xmlns:odi="http://opendope.org/components"
  xmlns:odgm="http://opendope.org/SmartArt/DataHierarchy"
  xmlns:ns24="http://schemas.openxmlformats.org/officeDocument/2006/bibliography"
  xmlns:ns25="http://schemas.openxmlformats.org/drawingml/2006/compatibility"
  xmlns:ns26="http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas">
  <w:body>
    <w:altChunk r:id="htmlChunk" />
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840" w:orient="portrait" />
      <w:pgMar w:top="1440"
               w:right="1440"
               w:bottom="1440"
               w:left="1440"
               w:header="720"
               w:footer="720"
               w:gutter="0"/>
    /w:sectPr
  /w:body
/w:document
PK
\00\00\00\00\00B,H1\B0\88'7\00\007\00\00\00\00\00word/afchunk.mhtMIME-Version: 1.0
Content-Type: multipart/related;
    type="text/html";
    boundary="----=mhtDocumentPart"
X-MimeOLE: Produced By Microsoft MimeOLE V6.1.7601.17609

This is a multi-part message in MIME format.

------=mhtDocumentPart
Content-Type: text/html;
    charset="utf-8"
Content-Transfer-Encoding: quoted-printable
Content-Location: file://\fake\document.html

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
    <meta http-equiv=3D"content-type" content=3D"text/html; charset=3Dutf-8">
    <title></title>
    <meta name=3D"generator" content=3D"LibreOffice 4.2.6.3 (Linux)">
    <meta name=3D"created" content=3D"20160112;33755000000000">
    <meta name=3D"changed" content=3D"0;0">
    <style type=3D"text/css">
    
    </style>
</head>
<body lang=3D"en-US" text=3D"#00000a" dir=3D"ltr">

<p class=3D"western" style=3D"margin-bottom: 0in; line-height: 100%">abc</p>

</body>
</html>

------=mhtDocumentPart--
PK
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00word/_rels/PK
\00\00\00\00\00B,HY!S\9A2\00\002\00\00\00\00\00word/_rels/document.xml.rels<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk"
    Target="/word/afchunk.mht" Id="htmlChunk" />
</Relationships>
PK\00
\00\00\00\00\00B,H\96%v\96\D1\00\00\D1\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00[Content_Types].xmlPK\00
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00_rels/PK\00
\00\00\00\00\00B,H\C2/\E5J\00\00J\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00&\00\00_rels/.relsPK\00
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\99\00\00word/PK\00
\00\00\00\00\00B,H"?!\E0\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\BC\00\00word/document.xmlPK\00
\00\00\00\00\00B,H1\B0\88'7\00\007\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\F3\00\00word/afchunk.mhtPK\00
\00\00\00\00\00B,H\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00X\00\00word/_rels/PK\00
\00\00\00\00\00B,HY!S\9A2\00\002\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\81\00\00word/_rels/document.xml.relsPK\00\00\00\00\00\00\E1\00\00\ED\00\00\00\00

**Comment by N1kto** [comment]
hello @lling1105 . what word processor do you open the output file on Ubuntu with?

**Comment by lling1105** [comment]
hi @N1kto I used LiberOffice to open the output file, but liberoffice can't open it correctly show as blank document. after then I use gedit to open the output and see many invalid charsets in it just as the previous post above. 
attached the output file.
[test3.docx](https://github.com/evidenceprime/html-docx-js-node-sample/files/88191/test3.docx)

**Comment by N1kto** [comment]
@lling1105, unfortunately, altchunks (the technique _html-docx-js_ is based on) is supported only by MS Office which means the produced document will not open in Liber/OpenOffice, MacOS Pages, Google Docs, etc. This is why you saw blank page in LibreOffice.
We put this info on the lib's [README](https://github.com/evidenceprime/html-docx-js#html-docx-js). You can get more info there.
