### ISSUE TITLE
Error : there are problems with the contents

### ISSUE THREAD

**Issue by spyshow** [evidenceprime/html-docx-js-node-sample#2]
hi
i have a problem when oppening the saved file ... it's giving me "the file Table.docx cannot be oppend because there are problems with the contents" ..... 
PS: i'm using it with dialog module from electron
here is my code : 
    
    var converted = htmlDocx.asBlob(docx);
                            dialog.showSaveDialog({
                                filters: [{ name: 'DOCX', extensions: ['docx']}],
                                title: 'Save the Table as Word file',
                                defaultPath: path.join(app.getPath('desktop'), 'Table.docx')}
                            , function(filename) {
                                fs.writeFile(filename, converted, function(err) {
                                    if (err) throw err;
                                });
                            
                            });

**Comment by anowak** [comment]
What version of MS Word are you using to open the file?

**Comment by spyshow** [comment]
Word 2010

**Comment by spyshow** [comment]
Any  reason for this error

**Comment by N1kto** [comment]
Can you attach the problematic file?

**Comment by spyshow** [comment]
[2.docx](https://github.com/evidenceprime/html-docx-js-node-sample/files/675708/2.docx)

**Comment by spyshow** [comment]
[1.docx](https://github.com/evidenceprime/html-docx-js-node-sample/files/675713/1.docx)

**Comment by N1kto** [comment]
It's not going to work like that with *electron*. Please refer to [this](https://github.com/evidenceprime/html-docx-js/issues/25) issue for info how to overcome that.

**Comment by spyshow** [comment]
hi ...  i used the code from the node sample but it's not working as you see ....

**Comment by N1kto** [comment]
But you are not using it in real `node` environment as you see, but in *electron*, which is kind of `browser` environment. That is why your generated file shows `[object Blob]`. `Blob` doesn't belong to `node` - there is `Buffer` instead.
If you want to use `html-docx-js` within *electron* app you should try the approach mentioned in the issue I referenced.

**Comment by spyshow** [comment]
it's just referring to use the node-sample ...

**Comment by N1kto** [comment]
Read the [last](https://github.com/evidenceprime/html-docx-js/issues/25#issuecomment-266301315) comment by @TamkeenLMS.

**Comment by nilay-patel-9spl** [comment]
> it's just referring to use the node-sample ...

Did you get it working with electron?
